app/__init__.py
from flask import Flask
from flask_bcrypt import Bcrypt
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_bootstrap import Bootstrap
from flask_mail import Mail

from config import Config

bcrypt = Bcrypt()
db = SQLAlchemy()
login = LoginManager()
login.login_view = 'auth.login'
login.login_message = 'Please log in to access this page.'
mail = Mail()
bootstrap = Bootstrap()


def create_app(config=Config):
    app = Flask(__name__)
    app.config.from_object(config)

    bcrypt.init_app(app)
    login.init_app(app)
    db.init_app(app)
    mail.init_app(app)
    bootstrap.init_app(app)

    from app.main.routes import main
    app.register_blueprint(main)

    from app.auth.routes import auth
    app.register_blueprint(auth)

    return app

from app import model

app/main/routes.py
from flask import Blueprint, render_template, redirect, url_for, request
from flask_login import login_required
import sqlite3 as sql
import os.path
from app.model import Log

main = Blueprint('main', __name__)

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
db_path = os.path.join(BASE_DIR + '/../../', "app.db")


@main.route('/')
@main.route('/index')
@login_required
def index():
    #
    con = sql.connect(db_path)
    con.row_factory = sql.Row
    cur = con.cursor()
    cur.execute("select * from main.calc")
    calcs = cur.fetchall()
    con.close()
    return render_template('main/index.html', calcs=calcs)


@main.route('/log')
@login_required
def log():
    con = sql.connect(db_path)
    con.row_factory = sql.Row
    cur = con.cursor()
    cur.execute("select * from main.calc_log order by id desc ")
    logs = cur.fetchall()
    con.close()
    return render_template('main/log.html', logs=logs)


@main.route('/admin')
@login_required
def admin():
    comments = [{'id': 1, 'name': 'dani', 'city': 'kras'}, {'id': 2, 'name': 'sanc', 'city': 'rostov'}]
    return render_template('main/admin.html')


@main.route('/add_log', methods=["POST"])
@login_required
def add_log():
    name = request.form["name"]
    id_calc = request.form["id_calc"]
    con = sql.connect(db_path)
    con.row_factory = sql.Row
    cur = con.cursor()
    cur.execute("INSERT INTO main.calc_log (time,id_calc,status,name,startdate,enddate,calcdate) "
                "VALUES(null, ?, 0, ?, datetime('now','localtime'), null , datetime('now','localtime'))", (id_calc, name))
    con.commit()
    con.close()
    return redirect(url_for('main.log'))


#
@main.route('/delete_log', methods=["POST"])
@login_required
def delete_log():
    id = request.form["id"]
    con = sql.connect(db_path)
    con.row_factory = sql.Row
    cur = con.cursor()
    cur.execute(
        "UPDATE main.calc_log SET time = (select strftime('%M','now', 'localtime') - strftime('%M', startdate) "
        "from main.calc_log where  id =?), status = 2, enddate = datetime('now','localtime') where id = ?;", (id, id))
    con.commit()
    con.close()
    return redirect(url_for('main.log'))

# @main.route("/delete", methods=["POST"])
# @login_required
# @app.route("/comment_delete", methods=["POST"])
# def comment_delete():
#     id = request.form["id"]
#     db_handler.delete_comment_by_id(id)
#     return redirect(url_for('view'))

app/templates/base.html
{% extends "bootstrap/base.html" %}
{% block title %}
  {% if title %}
    {{ title }}
  {% else %}
    Управление расчетами ЦО
  {% endif %}
{% endblock %}

{% block navbar %}
  {% include 'includes/_navbar.html' %}
{% endblock %}

{% block content %}
  <div class="container mt-3">
    {% block app_content %}
    {% endblock %}
  </div>
{% endblock %}

app/templates/bootstrap/base.html
{% block doc -%}
    <!DOCTYPE html>
    <html{% block html_attribs %}{% endblock html_attribs %}>
    {%- block html %}
        <head>
            {%- block head %}
                <title>{% block title %}{{ title|default }}{% endblock title %}</title>

                {%- block metas %}
                    <meta name="viewport" content="width=device-width, initial-scale=1.0">
                {%- endblock metas %}

                {%- block styles %}
                    <!-- Bootstrap -->
                    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
                    <!-- My Style -->
                    <link href="{{ url_for('static', filename='css/buttons-min.css') }}" rel="stylesheet">
                    <link href="{{ url_for('static', filename='css/buttons-core-min.css') }}" rel="stylesheet">
                    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
                {%- endblock styles %}
            {%- endblock head %}
        </head>
        <body{% block body_attribs %}{% endblock body_attribs %}>
        {% block body -%}
            {% block navbar %}
            {%- endblock navbar %}
            {% block content -%}
            {%- endblock content %}

            {% block scripts %}
                <script src="{{ url_for('static', filename='js/jquery-3.3.1.min.js') }}"></script>
                <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>

                <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
                <script src="{{ url_for('static', filename='js/bootstrap-confirmation.min.js') }}"></script>
                <script src="{{ url_for('static', filename='js/main.js') }}"></script>

            {%- endblock scripts %}
        {%- endblock body %}
        </body>
    {%- endblock html %}
    </html>
{% endblock doc -%}

app/templates/bootstrap/wtf.html
{% macro form_errors(form, hiddens=True) %}
  {%- if form.errors %}
    {%- for fieldname, errors in form.errors.items() %}
      {%- if bootstrap_is_hidden_field(form[fieldname]) and hiddens or
             not bootstrap_is_hidden_field(form[fieldname]) and hiddens != 'only' %}
        {%- for error in errors %}
          <p class="error">{{error}}</p>
        {%- endfor %}
      {%- endif %}
    {%- endfor %}
  {%- endif %}
{%- endmacro %}

{% macro _hz_form_wrap(horizontal_columns, form_type, add_group=False, required=False) %}
{% if form_type == "horizontal" %}
  {% if add_group %}<div class="form-group{% if required %} required{% endif %}">{% endif %}
  <div class="col-{{horizontal_columns[0]}}-offset-{{horizontal_columns[1]}}
              col-{{horizontal_columns[0]}}-{{horizontal_columns[2]}}
             ">
{% endif %}
{{caller()}}

{% if form_type == "horizontal" %}
  {% if add_group %}</div>{% endif %}
  </div>
{% endif %}
{% endmacro %}

{% macro form_field(field,
                    form_type="basic",
                    horizontal_columns=('lg', 2, 10),
                    button_map={}) %}

{# this is a workaround hack for the more straightforward-code of just passing required=required parameter. older versions of wtforms do not have
the necessary fix for required=False attributes, but will also not set the required flag in the first place. we skirt the issue using the code below #}
{% if field.flags.required and not required in kwargs %}
{% set kwargs = dict(required=True, **kwargs) %}
{% endif %}

{% if field.widget.input_type == 'checkbox' %}
  {% call _hz_form_wrap(horizontal_columns, form_type, True, required=required) %}
    <div class="checkbox">
      <label>
        {{field()|safe}} {{field.label.text|safe}}
      </label>
    </div>
  {% endcall %}
{%- elif field.type == 'RadioField' -%}
  {# note: A cleaner solution would be rendering depending on the widget,
     this is just a hack for now, until I can think of something better #}
  {% call _hz_form_wrap(horizontal_columns, form_type, True, required=required) %}
    {% for item in field -%}
      <div class="radio">
        <label>
          {{item|safe}} {{item.label.text|safe}}
        </label>
      </div>
    {% endfor %}
  {% endcall %}
{%- elif field.type == 'SubmitField' -%}
  {# deal with jinja scoping issues? #}
  {% set field_kwargs = kwargs %}

  {# note: same issue as above - should check widget, not field type #}
  {% call _hz_form_wrap(horizontal_columns, form_type, True, required=required) %}
    {{field(class='btn btn-%s' % button_map.get(field.name, 'default'),
            **field_kwargs)}}
  {% endcall %}
{%- elif field.type == 'FormField' -%}
{# note: FormFields are tricky to get right and complex setups requiring
   these are probably beyond the scope of what this macro tries to do.
   the code below ensures that things don't break horribly if we run into
   one, but does not try too hard to get things pretty. #}
  <fieldset>
    <legend>{{field.label}}</legend>
    {%- for subfield in field %}
      {% if not bootstrap_is_hidden_field(subfield) -%}
        {{ form_field(subfield,
                      form_type=form_type,
                      horizontal_columns=horizontal_columns,
                      button_map=button_map) }}
      {%- endif %}
    {%- endfor %}
  </fieldset>
{% else -%}
  <div class="form-group {%- if field.flags.required %} required{% endif -%}">
      {%- if form_type == "inline" %}
        {{field.label(class="sr-only")|safe}}
        {% if field.type == 'FileField' %}
          {{field(**kwargs)|safe}}
        {% else %}
          {{field(class="form-control", **kwargs)|safe}}
        {% endif %}
      {% elif form_type == "horizontal" %}
        {{field.label(class="control-label " + (
          " col-%s-%s" % horizontal_columns[0:2]
        ))|safe}}
        <div class=" col-{{horizontal_columns[0]}}-{{horizontal_columns[2]}}">
          {% if field.type == 'FileField' %}
            {{field(**kwargs)|safe}}
          {% else %}
            {{field(class="form-control", **kwargs)|safe}}
          {% endif %}
        </div>
        {%- if field.errors %}
          {%- for error in field.errors %}
            {% call _hz_form_wrap(horizontal_columns, form_type, required=required) %}
              <p class="text-danger">{{error}}</p>
            {% endcall %}
          {%- endfor %}
        {%- elif field.description -%}
          {% call _hz_form_wrap(horizontal_columns, form_type, required=required) %}
            <p class="help-block">{{field.description|safe}}</p>
          {% endcall %}
        {%- endif %}
      {%- else -%}
        {{field.label(class="control-label")|safe}}
        {% if field.type == 'FileField' %}
          {{field(**kwargs)|safe}}
        {% else %}
          {{field(class="form-control", **kwargs)|safe}}
        {% endif %}

        {%- if field.errors %}
          {%- for error in field.errors %}
            <p class="text-danger">{{error}}</p>
          {%- endfor %}
        {%- elif field.description -%}
          <p class="help-block">{{field.description|safe}}</p>
        {%- endif %}
      {%- endif %}
  </div>
{% endif %}
{% endmacro %}

{# valid form types are "basic", "inline" and "horizontal" #}
{% macro quick_form(form,
                    action="",
                    method="post",
                    extra_classes=None,
                    role="form",
                    form_type="basic",
                    horizontal_columns=('lg', 2, 10),
                    enctype=None,
                    button_map={},
                    id="") %}
{#-
action="" is what we want, from http://www.ietf.org/rfc/rfc2396.txt:

4.2. Same-document References

   A URI reference that does not contain a URI is a reference to the
   current document.  In other words, an empty URI reference within a
   document is interpreted as a reference to the start of that document,
   and a reference containing only a fragment identifier is a reference
   to the identified fragment of that document.  Traversal of such a
   reference should not result in an additional retrieval action.
   However, if the URI reference occurs in a context that is always
   intended to result in a new request, as in the case of HTML's FORM
   element, then an empty URI reference represents the base URI of the
   current document and should be replaced by that URI when transformed
   into a request.

 -#}
{#- if any file fields are inside the form and enctype is automatic, adjust
    if file fields are found. could really use the equalto test of jinja2
    here, but latter is not available until 2.8

    warning: the code below is guaranteed to make you cry =(
#}
{%- set _enctype = [] %}
{%- if enctype is none -%}
  {%- for field in form %}
    {%- if field.type == 'FileField' %}
      {#- for loops come with a fairly watertight scope, so this list-hack is
          used to be able to set values outside of it #}
      {%- set _ = _enctype.append('multipart/form-data') -%}
    {%- endif %}
  {%- endfor %}
{%- else %}
  {% set _ = _enctype.append(enctype) %}
{%- endif %}
<form
  {%- if action != None %} action="{{action}}"{% endif -%}
  {%- if id %} id="{{id}}"{% endif -%}
  {%- if method %} method="{{method}}"{% endif %}
  class="form
    {%- if extra_classes %} {{extra_classes}}{% endif -%}
    {%- if form_type == "horizontal" %} form-horizontal
    {%- elif form_type == "inline" %} form-inline
    {%- endif -%}
  "
  {%- if _enctype[0] %} enctype="{{_enctype[0]}}"{% endif -%}
  {%- if role %} role="{{role}}"{% endif -%}
  >
  {{ form.hidden_tag() }}
  {{ form_errors(form, hiddens='only') }}

  {%- for field in form %}
    {% if not bootstrap_is_hidden_field(field) -%}
      {{ form_field(field,
                    form_type=form_type,
                    horizontal_columns=horizontal_columns,
                    button_map=button_map) }}
    {%- endif %}
  {%- endfor %}

</form>
{%- endmacro %}

app/templates/includes/_messages.html
{%- with messages = get_flashed_messages(with_categories=true) -%}
  {% if messages %}
    {% for category, message in messages %}
      {% if category == 'message' %}
        <div class="alert alert-{{ category }}">{{ message }}</div>
      {% else %}
        <div class="alert alert-info">{{ message }}</div>
      {% endif %}
    {% endfor %}
  {% endif %}
{%- endwith %}

app/templates/includes/_navbar.html
<nav class="navbar navbar-expand-sm navbar-dark" style="background-color: #ac452c;">
    <div class="container">
        {% if current_user.is_authenticated %}
            <a class="navbar-brand" href="{{ url_for('main.index') }}">Расчеты ЦО</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav">
                <span class="navbar-toggler-icon"></span>
            </button>

            <a class="navbar-brand" href="{{ url_for('main.log') }}">Логи расчетов</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav">
                <span class="navbar-toggler-icon"></span>
            </button>
            {% if current_user.username == 'admin' %}
                <a class="navbar-brand" href="{{ url_for('main.admin') }}">Настройки расчетов</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav">
                    <span class="navbar-toggler-icon"></span>
                </button>
            {% endif %}

            <div class="collapse navbar-collapse" id="nav">
        {% endif %}
        <ul class="navbar-nav ml-auto">
            {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">Выход</a>
                </li>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav">
                <span class="navbar-toggler-icon"></span>
                <ul class="navbar-nav mr-auto">
                    {#                <li class="nav-item {% if request.path == url_for('main.index') %}active{% endif %}">#}
                    {#                    <a class="nav-link" href="{{ url_for('main.index') }}">Домой</a>#}
                    {#                </li>#}
                    <li class="nav-item {% if request.path == url_for('main.log') %}active{% endif %}">
                        <a class="nav-link" href="{{ url_for('main.log') }}">Логи расчетов</a>
                    </li>
                    {% if current_user.username == 'admin' %}
                        <li class="nav-item {% if request.path == url_for('main.admin') %}active{% endif %}">
                            <a class="nav-link" href="{{ url_for('main.admin') }}">Настройки</a>
                        </li>
                    {% endif %}
                </ul>
            {% else %}
                <li class="nav-item {% if request.path == url_for('auth.login') %}active{% endif %}">
                    <a class="nav-link" href="{{ url_for('auth.login') }}">Вход</a>
                </li>
{#                                    <li class="nav-item {% if request.path == url_for('auth.register') %}active{% endif %}">#}
{#                                        <a class="nav-link" href="{{ url_for('auth.register') }}">Регистрация</a>#}
{#                                    </li>#}
            {% endif %}
        </ul>
        </div>
    </div>
</nav>

app/templates/main/admin.html
<script type="text/javascript">
    function check(field, flag) {
        if (flag === 1) {
            for (i = 0; i < field.length; i++) {
                field[i].checked = true;
            }
        }
        else {
            for (i = 0; i < field.length; i++) {
                field[i].checked = false;
            }
        }
    }
</script>

{% extends 'base.html' %}
{% block app_content %}


    <form name="select_all" method="post" style="margin-left:35px;">
        <b>Рассчитываемые МХ:</b><br>
        <input type="checkbox" name="list" value="1">Краснодар 1<br>
        <input type="checkbox" name="list" value="2">Краснодар 2<br>
        <input type="checkbox" name="list" value="3">Краснодар 3<br>
        <input type="checkbox" name="list" value="4">Краснодар 3<br>
        <input type="checkbox" name="list" value="5">Краснодар 4<br>
        <input type="checkbox" name="list" value="6">Краснодар 5<br><br>
        <input type="button" value="Выделить все" onclick="check(this.form.list,1)">
        <input type="button" value="Снять выделение" onclick="check(this.form.list,0)">
    </form>
    <br>


    <div class="slidecontainer">
        <b>Ограничние параллелей расчетов </b><br>
        <br>
        <input type="range" min="0" max="64" value="32" step="8" class="slider" id="myRange">
        <span id="demo" style="font-weight:bold;color:red"></span>
    </div>

    <br>

    <br>
    <b>Диагностика и трассировка </b><br>
    <br>
    <div class="bootstrap-switch-square">
        <input type="checkbox" data-toggle="switch" name="Resend" id="Resend"/> ВКЛ/ВЫКЛ
    </div>
    <br>
    <br>

    {#    <div class="range">#}
    {#        <label for="formControlRange">Ограничить параллели для расчетов</label>#}
    {#        <input type="range" class="form-control-range" id="formControlRange">#}
    {#    </div>#}



{% endblock %}

app/templates/main/delete.html
{% extends 'base.html' %}
{% block app_content %}

      <h1>Расчет успешно завершен </h1>
{% endblock %}

app/templates/main/index.html
{% extends 'base.html' %}
{% block app_content %}
{#    <h1>Добрый день </h1>#}

{#    {% block title %}Просмотр{% endblock %}#}
    <h1>Расчеты</h1>
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">Номер</th>
            <th scope="col">Название</th>
            <td></td>
        </tr>
        </thead>
        <tbody>
        {% for calc in calcs %}
            <tr>
                <td>{{ calc["id_calc"] }}</td>
                <td>{{ calc["name"] }}</td>
                <td class="text-right">
                    <div class="row">
                        <form action="{{ url_for('main.add_log') }}" method="post" class="pull-right">
                            <input type="hidden" name="id_calc" value="{{ calc["id_calc"] }}">
                            <input type="hidden" name="name" value="{{ calc["name"] }}">
                            <input type="submit" class="btn btn-primary pull-right" data-toggle="confirmation"
                                   data-btn-ok-label="Да" data-btn-ok-class="btn-success"
                                   data-btn-cancel-label="Нет" data-btn-cancel-class="btn-danger"
                                   data-title="Действительно запустить?" value="Запустить">
                        </form>
{#                        <a class="btn btn-primary pull-right"#}
{#                           href="">Запустить</a>#}
                    </div>
                </td>
            </tr>
            </tbody>
        {% endfor %}
    </table>

{% endblock %}

app/templates/main/log.html
{% extends 'base.html' %}
{% block app_content %}
    {#    <h1>Добрый день </h1>#}

    {#    {% block title %}Просмотр{% endblock %}#}
    <h1>Запущенные расчеты ЦО</h1>
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">Время выполнения</th>
            <th scope="col">Номер</th>
            <th scope="col">Статус</th>
            <th scope="col">Название</th>
            <th scope="col">Дата запуска</th>
            <th scope="col">Дата завершения</th>
            <th scope="col">Расчетная дата</th>
            <td></td>
        </tr>
        </thead>
        <tbody>
        {% for log in logs %}
            <tr>
                <td>{{ log["time"] }}</td>
                <td>{{ log["id_calc"] }}</td>
                <td>{{ log["status"] }}</td>
                <td>{{ log["name"] }}</td>
                <td>{{ log["startdate"] }}</td>
                <td>{{ log["enddate"] }}</td>
                <td>{{ log["calcdate"] }}</td>
                <td class="text-right">
                    <div class="row">
                        <form action="{{ url_for('main.delete_log') }}" method="post" class="pull-right">
                            <input type="hidden" name="id" value="{{ log["id"] }}">
                            <input type="submit" class="btn btn-danger" data-toggle="confirmation"
                                   data-btn-ok-label="Да" data-btn-ok-class="btn-success"
                                   data-btn-cancel-label="Нет" data-btn-cancel-class="btn-danger"
                                   data-title="Действительно остановить?" value="Остановить">
                        </form>
{#                        <a class="btn btn-primary pull-right"#}
{#                           href="">Перезапустить</a>#}
                    </div>
                </td>
            </tr>
            </tbody>
        {% endfor %}
    </table>

{% endblock %}